### ISSUE TITLE
Use XDG spec for location of otrkey_cache file

### ISSUE THREAD

**Issue by Leseratte10** [otrtool/otrtool#20]
Would it be possible to follow the XDG spec when deciding where to read/write the otrkey cache file so it doesn't clutter the user's home directory? 

Meaning, only read `$HOME/.otrkey_cache` if already present, and if it's not present fall back to reading / writing either `$XDG_CONFIG_HOME/otrkey_cache` (or, if $XDG_CONFIG_HOME isn't set, `$HOME/.config/otrkey_cache`). 

Usually, cache data would go into $XDG_CACHE_HOME, but that's usually for data that doesn't need to be backed up and has no consequences when it gets deleted, which isn't really the case for OTRkeys so it should either go into XDG_CONFIG_HOME or XDG_DATA_HOME.

**Comment by eshrdlu** [comment]
It would definitely be possible and has been an issue since the key cache feature was included (see https://github.com/otrtool/otrtool/pull/3#issuecomment-20946979).

I think `$XDG_DATA_HOME/otrtool/otrkey_cache` would be most fitting.

I'm not sure if I want to make it the default though (when no key cache file exists yet), but that's mainly because I personally prefer the "old school" dot files.
